/*
 * This file is generated by jOOQ.
 */
package com.financial.loan.persistence.model.tables.records;


import com.financial.loan.persistence.model.tables.ApplicationHistory;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ApplicationHistoryRecord extends UpdatableRecordImpl<ApplicationHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.application_history.id</code>.
     */
    public ApplicationHistoryRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.application_history.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.application_history.application_id</code>.
     */
    public ApplicationHistoryRecord setApplicationId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.application_history.application_id</code>.
     */
    public Integer getApplicationId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.application_history.old_status</code>.
     */
    public ApplicationHistoryRecord setOldStatus(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.application_history.old_status</code>.
     */
    public String getOldStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.application_history.new_status</code>.
     */
    public ApplicationHistoryRecord setNewStatus(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.application_history.new_status</code>.
     */
    public String getNewStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.application_history.created_at</code>.
     */
    public ApplicationHistoryRecord setCreatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.application_history.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.application_history.changed_at</code>.
     */
    public ApplicationHistoryRecord setChangedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.application_history.changed_at</code>.
     */
    public LocalDateTime getChangedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApplicationHistoryRecord
     */
    public ApplicationHistoryRecord() {
        super(ApplicationHistory.APPLICATION_HISTORY);
    }

    /**
     * Create a detached, initialised ApplicationHistoryRecord
     */
    public ApplicationHistoryRecord(Integer id, Integer applicationId, String oldStatus, String newStatus, LocalDateTime createdAt, LocalDateTime changedAt) {
        super(ApplicationHistory.APPLICATION_HISTORY);

        setId(id);
        setApplicationId(applicationId);
        setOldStatus(oldStatus);
        setNewStatus(newStatus);
        setCreatedAt(createdAt);
        setChangedAt(changedAt);
        resetTouchedOnNotNull();
    }
}
