/*
 * This file is generated by jOOQ.
 */
package com.financial.loan.persistence.model.tables.records;


import com.financial.loan.persistence.model.tables.Car;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CarRecord extends UpdatableRecordImpl<CarRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.car.id</code>.
     */
    public CarRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.car.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.car.brand</code>.
     */
    public CarRecord setBrand(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.car.brand</code>.
     */
    public String getBrand() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.car.model</code>.
     */
    public CarRecord setModel(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.car.model</code>.
     */
    public String getModel() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.car.year</code>.
     */
    public CarRecord setYear(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.car.year</code>.
     */
    public Integer getYear() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.car.cost</code>.
     */
    public CarRecord setCost(Double value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.car.cost</code>.
     */
    public Double getCost() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>public.car.created_at</code>.
     */
    public CarRecord setCreatedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.car.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.car.updated_at</code>.
     */
    public CarRecord setUpdatedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.car.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CarRecord
     */
    public CarRecord() {
        super(Car.CAR);
    }

    /**
     * Create a detached, initialised CarRecord
     */
    public CarRecord(Integer id, String brand, String model, Integer year, Double cost, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Car.CAR);

        setId(id);
        setBrand(brand);
        setModel(model);
        setYear(year);
        setCost(cost);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
