/*
 * This file is generated by jOOQ.
 */
package com.financial.loan.persistence.model.tables.records;


import com.financial.loan.persistence.model.tables.LoanApplication;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LoanApplicationRecord extends UpdatableRecordImpl<LoanApplicationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.loan_application.id</code>.
     */
    public LoanApplicationRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.loan_application.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.loan_application.car_id</code>.
     */
    public LoanApplicationRecord setCarId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.loan_application.car_id</code>.
     */
    public Integer getCarId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.loan_application.user_id</code>.
     */
    public LoanApplicationRecord setUserId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.loan_application.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.loan_application.loan_amount</code>.
     */
    public LoanApplicationRecord setLoanAmount(Double value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.loan_application.loan_amount</code>.
     */
    public Double getLoanAmount() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.loan_application.first_payment</code>.
     */
    public LoanApplicationRecord setFirstPayment(Double value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.loan_application.first_payment</code>.
     */
    public Double getFirstPayment() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>public.loan_application.term_month</code>.
     */
    public LoanApplicationRecord setTermMonth(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.loan_application.term_month</code>.
     */
    public Integer getTermMonth() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.loan_application.status</code>.
     */
    public LoanApplicationRecord setStatus(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.loan_application.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.loan_application.created_at</code>.
     */
    public LoanApplicationRecord setCreatedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.loan_application.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.loan_application.updated_at</code>.
     */
    public LoanApplicationRecord setUpdatedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.loan_application.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LoanApplicationRecord
     */
    public LoanApplicationRecord() {
        super(LoanApplication.LOAN_APPLICATION);
    }

    /**
     * Create a detached, initialised LoanApplicationRecord
     */
    public LoanApplicationRecord(Integer id, Integer carId, Integer userId, Double loanAmount, Double firstPayment, Integer termMonth, String status, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(LoanApplication.LOAN_APPLICATION);

        setId(id);
        setCarId(carId);
        setUserId(userId);
        setLoanAmount(loanAmount);
        setFirstPayment(firstPayment);
        setTermMonth(termMonth);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
