/*
 * This file is generated by jOOQ.
 */
package com.financial.loan.persistence.model.tables.records;


import com.financial.loan.persistence.model.tables.UserAdditionalData;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserAdditionalDataRecord extends UpdatableRecordImpl<UserAdditionalDataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_additional_data.id</code>.
     */
    public UserAdditionalDataRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.user_additional_data.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.user_additional_data.user_id</code>.
     */
    public UserAdditionalDataRecord setUserId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.user_additional_data.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.user_additional_data.birthday</code>.
     */
    public UserAdditionalDataRecord setBirthday(LocalDate value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.user_additional_data.birthday</code>.
     */
    public LocalDate getBirthday() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>public.user_additional_data.passport_series</code>.
     */
    public UserAdditionalDataRecord setPassportSeries(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.user_additional_data.passport_series</code>.
     */
    public String getPassportSeries() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.user_additional_data.passport_number</code>.
     */
    public UserAdditionalDataRecord setPassportNumber(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.user_additional_data.passport_number</code>.
     */
    public String getPassportNumber() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.user_additional_data.monthly_income</code>.
     */
    public UserAdditionalDataRecord setMonthlyIncome(Double value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.user_additional_data.monthly_income</code>.
     */
    public Double getMonthlyIncome() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>public.user_additional_data.created_at</code>.
     */
    public UserAdditionalDataRecord setCreatedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.user_additional_data.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.user_additional_data.updated_at</code>.
     */
    public UserAdditionalDataRecord setUpdatedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.user_additional_data.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserAdditionalDataRecord
     */
    public UserAdditionalDataRecord() {
        super(UserAdditionalData.USER_ADDITIONAL_DATA);
    }

    /**
     * Create a detached, initialised UserAdditionalDataRecord
     */
    public UserAdditionalDataRecord(Integer id, Integer userId, LocalDate birthday, String passportSeries, String passportNumber, Double monthlyIncome, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(UserAdditionalData.USER_ADDITIONAL_DATA);

        setId(id);
        setUserId(userId);
        setBirthday(birthday);
        setPassportSeries(passportSeries);
        setPassportNumber(passportNumber);
        setMonthlyIncome(monthlyIncome);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
