/*
 * This file is generated by jOOQ.
 */
package com.financial.loan.persistence.model;


import com.financial.loan.persistence.model.tables.ApplicationHistory;
import com.financial.loan.persistence.model.tables.Car;
import com.financial.loan.persistence.model.tables.LoanApplication;
import com.financial.loan.persistence.model.tables.User;
import com.financial.loan.persistence.model.tables.UserAdditionalData;
import com.financial.loan.persistence.model.tables.records.ApplicationHistoryRecord;
import com.financial.loan.persistence.model.tables.records.CarRecord;
import com.financial.loan.persistence.model.tables.records.LoanApplicationRecord;
import com.financial.loan.persistence.model.tables.records.UserAdditionalDataRecord;
import com.financial.loan.persistence.model.tables.records.UserRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ApplicationHistoryRecord> APPLICATION_HISTORY_PKEY = Internal.createUniqueKey(ApplicationHistory.APPLICATION_HISTORY, DSL.name("application_history_pkey"), new TableField[] { ApplicationHistory.APPLICATION_HISTORY.ID }, true);
    public static final UniqueKey<CarRecord> CAR_PKEY = Internal.createUniqueKey(Car.CAR, DSL.name("car_pkey"), new TableField[] { Car.CAR.ID }, true);
    public static final UniqueKey<LoanApplicationRecord> LOAN_APPLICATION_CAR_ID_KEY = Internal.createUniqueKey(LoanApplication.LOAN_APPLICATION, DSL.name("loan_application_car_id_key"), new TableField[] { LoanApplication.LOAN_APPLICATION.CAR_ID }, true);
    public static final UniqueKey<LoanApplicationRecord> LOAN_APPLICATION_PKEY = Internal.createUniqueKey(LoanApplication.LOAN_APPLICATION, DSL.name("loan_application_pkey"), new TableField[] { LoanApplication.LOAN_APPLICATION.ID }, true);
    public static final UniqueKey<UserRecord> USER_PKEY = Internal.createUniqueKey(User.USER, DSL.name("user_pkey"), new TableField[] { User.USER.ID }, true);
    public static final UniqueKey<UserAdditionalDataRecord> USER_ADDITIONAL_DATA_PKEY = Internal.createUniqueKey(UserAdditionalData.USER_ADDITIONAL_DATA, DSL.name("user_additional_data_pkey"), new TableField[] { UserAdditionalData.USER_ADDITIONAL_DATA.ID }, true);
    public static final UniqueKey<UserAdditionalDataRecord> USER_ADDITIONAL_DATA_USER_ID_KEY = Internal.createUniqueKey(UserAdditionalData.USER_ADDITIONAL_DATA, DSL.name("user_additional_data_user_id_key"), new TableField[] { UserAdditionalData.USER_ADDITIONAL_DATA.USER_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ApplicationHistoryRecord, LoanApplicationRecord> APPLICATION_HISTORY__APPLICATION_HISTORY_APPLICATION_ID_FKEY = Internal.createForeignKey(ApplicationHistory.APPLICATION_HISTORY, DSL.name("application_history_application_id_fkey"), new TableField[] { ApplicationHistory.APPLICATION_HISTORY.APPLICATION_ID }, Keys.LOAN_APPLICATION_PKEY, new TableField[] { LoanApplication.LOAN_APPLICATION.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<LoanApplicationRecord, CarRecord> LOAN_APPLICATION__LOAN_APPLICATION_CAR_ID_FKEY = Internal.createForeignKey(LoanApplication.LOAN_APPLICATION, DSL.name("loan_application_car_id_fkey"), new TableField[] { LoanApplication.LOAN_APPLICATION.CAR_ID }, Keys.CAR_PKEY, new TableField[] { Car.CAR.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<LoanApplicationRecord, UserRecord> LOAN_APPLICATION__LOAN_APPLICATION_USER_ID_FKEY = Internal.createForeignKey(LoanApplication.LOAN_APPLICATION, DSL.name("loan_application_user_id_fkey"), new TableField[] { LoanApplication.LOAN_APPLICATION.USER_ID }, Keys.USER_PKEY, new TableField[] { User.USER.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<UserAdditionalDataRecord, UserRecord> USER_ADDITIONAL_DATA__USER_ADDITIONAL_DATA_USER_ID_FKEY = Internal.createForeignKey(UserAdditionalData.USER_ADDITIONAL_DATA, DSL.name("user_additional_data_user_id_fkey"), new TableField[] { UserAdditionalData.USER_ADDITIONAL_DATA.USER_ID }, Keys.USER_PKEY, new TableField[] { User.USER.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
