/*
 * This file is generated by jOOQ.
 */
package com.financial.loan.persistence.model;


import com.financial.loan.persistence.model.tables.ApplicationHistory;
import com.financial.loan.persistence.model.tables.Car;
import com.financial.loan.persistence.model.tables.LoanApplication;
import com.financial.loan.persistence.model.tables.User;
import com.financial.loan.persistence.model.tables.UserAdditionalData;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * standard public schema
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.application_history</code>.
     */
    public final ApplicationHistory APPLICATION_HISTORY = ApplicationHistory.APPLICATION_HISTORY;

    /**
     * The table <code>public.car</code>.
     */
    public final Car CAR = Car.CAR;

    /**
     * The table <code>public.loan_application</code>.
     */
    public final LoanApplication LOAN_APPLICATION = LoanApplication.LOAN_APPLICATION;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>public.user_additional_data</code>.
     */
    public final UserAdditionalData USER_ADDITIONAL_DATA = UserAdditionalData.USER_ADDITIONAL_DATA;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ApplicationHistory.APPLICATION_HISTORY,
            Car.CAR,
            LoanApplication.LOAN_APPLICATION,
            User.USER,
            UserAdditionalData.USER_ADDITIONAL_DATA
        );
    }
}
