/*
 * This file is generated by jOOQ.
 */
package com.financial.loan.persistence.model;


import com.financial.loan.persistence.model.tables.ApplicationHistory;
import com.financial.loan.persistence.model.tables.Car;
import com.financial.loan.persistence.model.tables.LoanApplication;
import com.financial.loan.persistence.model.tables.User;
import com.financial.loan.persistence.model.tables.UserAdditionalData;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.application_history</code>.
     */
    public static final ApplicationHistory APPLICATION_HISTORY = ApplicationHistory.APPLICATION_HISTORY;

    /**
     * The table <code>public.car</code>.
     */
    public static final Car CAR = Car.CAR;

    /**
     * The table <code>public.loan_application</code>.
     */
    public static final LoanApplication LOAN_APPLICATION = LoanApplication.LOAN_APPLICATION;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>public.user_additional_data</code>.
     */
    public static final UserAdditionalData USER_ADDITIONAL_DATA = UserAdditionalData.USER_ADDITIONAL_DATA;
}
