/*
 * This file is generated by jOOQ.
 */
package com.financial.loan.persistence.model.tables;


import com.financial.loan.persistence.model.Keys;
import com.financial.loan.persistence.model.Public;
import com.financial.loan.persistence.model.tables.LoanApplication.LoanApplicationPath;
import com.financial.loan.persistence.model.tables.records.ApplicationHistoryRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ApplicationHistory extends TableImpl<ApplicationHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.application_history</code>
     */
    public static final ApplicationHistory APPLICATION_HISTORY = new ApplicationHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ApplicationHistoryRecord> getRecordType() {
        return ApplicationHistoryRecord.class;
    }

    /**
     * The column <code>public.application_history.id</code>.
     */
    public final TableField<ApplicationHistoryRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.application_history.application_id</code>.
     */
    public final TableField<ApplicationHistoryRecord, Integer> APPLICATION_ID = createField(DSL.name("application_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.application_history.old_status</code>.
     */
    public final TableField<ApplicationHistoryRecord, String> OLD_STATUS = createField(DSL.name("old_status"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.application_history.new_status</code>.
     */
    public final TableField<ApplicationHistoryRecord, String> NEW_STATUS = createField(DSL.name("new_status"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.application_history.created_at</code>.
     */
    public final TableField<ApplicationHistoryRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.application_history.changed_at</code>.
     */
    public final TableField<ApplicationHistoryRecord, LocalDateTime> CHANGED_AT = createField(DSL.name("changed_at"), SQLDataType.LOCALDATETIME(6), this, "");

    private ApplicationHistory(Name alias, Table<ApplicationHistoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ApplicationHistory(Name alias, Table<ApplicationHistoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.application_history</code> table reference
     */
    public ApplicationHistory(String alias) {
        this(DSL.name(alias), APPLICATION_HISTORY);
    }

    /**
     * Create an aliased <code>public.application_history</code> table reference
     */
    public ApplicationHistory(Name alias) {
        this(alias, APPLICATION_HISTORY);
    }

    /**
     * Create a <code>public.application_history</code> table reference
     */
    public ApplicationHistory() {
        this(DSL.name("application_history"), null);
    }

    public <O extends Record> ApplicationHistory(Table<O> path, ForeignKey<O, ApplicationHistoryRecord> childPath, InverseForeignKey<O, ApplicationHistoryRecord> parentPath) {
        super(path, childPath, parentPath, APPLICATION_HISTORY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ApplicationHistoryPath extends ApplicationHistory implements Path<ApplicationHistoryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ApplicationHistoryPath(Table<O> path, ForeignKey<O, ApplicationHistoryRecord> childPath, InverseForeignKey<O, ApplicationHistoryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ApplicationHistoryPath(Name alias, Table<ApplicationHistoryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ApplicationHistoryPath as(String alias) {
            return new ApplicationHistoryPath(DSL.name(alias), this);
        }

        @Override
        public ApplicationHistoryPath as(Name alias) {
            return new ApplicationHistoryPath(alias, this);
        }

        @Override
        public ApplicationHistoryPath as(Table<?> alias) {
            return new ApplicationHistoryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ApplicationHistoryRecord, Integer> getIdentity() {
        return (Identity<ApplicationHistoryRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ApplicationHistoryRecord> getPrimaryKey() {
        return Keys.APPLICATION_HISTORY_PKEY;
    }

    @Override
    public List<ForeignKey<ApplicationHistoryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.APPLICATION_HISTORY__APPLICATION_HISTORY_APPLICATION_ID_FKEY);
    }

    private transient LoanApplicationPath _loanApplication;

    /**
     * Get the implicit join path to the <code>public.loan_application</code>
     * table.
     */
    public LoanApplicationPath loanApplication() {
        if (_loanApplication == null)
            _loanApplication = new LoanApplicationPath(this, Keys.APPLICATION_HISTORY__APPLICATION_HISTORY_APPLICATION_ID_FKEY, null);

        return _loanApplication;
    }

    @Override
    public ApplicationHistory as(String alias) {
        return new ApplicationHistory(DSL.name(alias), this);
    }

    @Override
    public ApplicationHistory as(Name alias) {
        return new ApplicationHistory(alias, this);
    }

    @Override
    public ApplicationHistory as(Table<?> alias) {
        return new ApplicationHistory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ApplicationHistory rename(String name) {
        return new ApplicationHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ApplicationHistory rename(Name name) {
        return new ApplicationHistory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ApplicationHistory rename(Table<?> name) {
        return new ApplicationHistory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ApplicationHistory where(Condition condition) {
        return new ApplicationHistory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ApplicationHistory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ApplicationHistory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ApplicationHistory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ApplicationHistory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ApplicationHistory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ApplicationHistory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ApplicationHistory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ApplicationHistory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ApplicationHistory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
