/*
 * This file is generated by jOOQ.
 */
package com.financial.loan.persistence.model.tables;


import com.financial.loan.persistence.model.Keys;
import com.financial.loan.persistence.model.Public;
import com.financial.loan.persistence.model.tables.LoanApplication.LoanApplicationPath;
import com.financial.loan.persistence.model.tables.records.CarRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Car extends TableImpl<CarRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.car</code>
     */
    public static final Car CAR = new Car();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CarRecord> getRecordType() {
        return CarRecord.class;
    }

    /**
     * The column <code>public.car.id</code>.
     */
    public final TableField<CarRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.car.brand</code>.
     */
    public final TableField<CarRecord, String> BRAND = createField(DSL.name("brand"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.car.model</code>.
     */
    public final TableField<CarRecord, String> MODEL = createField(DSL.name("model"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.car.year</code>.
     */
    public final TableField<CarRecord, Integer> YEAR = createField(DSL.name("year"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.car.cost</code>.
     */
    public final TableField<CarRecord, Double> COST = createField(DSL.name("cost"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.car.created_at</code>.
     */
    public final TableField<CarRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.car.updated_at</code>.
     */
    public final TableField<CarRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    private Car(Name alias, Table<CarRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Car(Name alias, Table<CarRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.car</code> table reference
     */
    public Car(String alias) {
        this(DSL.name(alias), CAR);
    }

    /**
     * Create an aliased <code>public.car</code> table reference
     */
    public Car(Name alias) {
        this(alias, CAR);
    }

    /**
     * Create a <code>public.car</code> table reference
     */
    public Car() {
        this(DSL.name("car"), null);
    }

    public <O extends Record> Car(Table<O> path, ForeignKey<O, CarRecord> childPath, InverseForeignKey<O, CarRecord> parentPath) {
        super(path, childPath, parentPath, CAR);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CarPath extends Car implements Path<CarRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CarPath(Table<O> path, ForeignKey<O, CarRecord> childPath, InverseForeignKey<O, CarRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CarPath(Name alias, Table<CarRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CarPath as(String alias) {
            return new CarPath(DSL.name(alias), this);
        }

        @Override
        public CarPath as(Name alias) {
            return new CarPath(alias, this);
        }

        @Override
        public CarPath as(Table<?> alias) {
            return new CarPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<CarRecord, Integer> getIdentity() {
        return (Identity<CarRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<CarRecord> getPrimaryKey() {
        return Keys.CAR_PKEY;
    }

    private transient LoanApplicationPath _loanApplication;

    /**
     * Get the implicit to-many join path to the
     * <code>public.loan_application</code> table
     */
    public LoanApplicationPath loanApplication() {
        if (_loanApplication == null)
            _loanApplication = new LoanApplicationPath(this, null, Keys.LOAN_APPLICATION__LOAN_APPLICATION_CAR_ID_FKEY.getInverseKey());

        return _loanApplication;
    }

    @Override
    public Car as(String alias) {
        return new Car(DSL.name(alias), this);
    }

    @Override
    public Car as(Name alias) {
        return new Car(alias, this);
    }

    @Override
    public Car as(Table<?> alias) {
        return new Car(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Car rename(String name) {
        return new Car(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Car rename(Name name) {
        return new Car(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Car rename(Table<?> name) {
        return new Car(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Car where(Condition condition) {
        return new Car(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Car where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Car where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Car where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Car where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Car where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Car where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Car where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Car whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Car whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
