/*
 * This file is generated by jOOQ.
 */
package com.financial.loan.persistence.model.tables;


import com.financial.loan.persistence.model.Keys;
import com.financial.loan.persistence.model.Public;
import com.financial.loan.persistence.model.tables.ApplicationHistory.ApplicationHistoryPath;
import com.financial.loan.persistence.model.tables.Car.CarPath;
import com.financial.loan.persistence.model.tables.User.UserPath;
import com.financial.loan.persistence.model.tables.records.LoanApplicationRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LoanApplication extends TableImpl<LoanApplicationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.loan_application</code>
     */
    public static final LoanApplication LOAN_APPLICATION = new LoanApplication();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LoanApplicationRecord> getRecordType() {
        return LoanApplicationRecord.class;
    }

    /**
     * The column <code>public.loan_application.id</code>.
     */
    public final TableField<LoanApplicationRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.loan_application.car_id</code>.
     */
    public final TableField<LoanApplicationRecord, Integer> CAR_ID = createField(DSL.name("car_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.loan_application.user_id</code>.
     */
    public final TableField<LoanApplicationRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.loan_application.loan_amount</code>.
     */
    public final TableField<LoanApplicationRecord, Double> LOAN_AMOUNT = createField(DSL.name("loan_amount"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.loan_application.first_payment</code>.
     */
    public final TableField<LoanApplicationRecord, Double> FIRST_PAYMENT = createField(DSL.name("first_payment"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.loan_application.term_month</code>.
     */
    public final TableField<LoanApplicationRecord, Integer> TERM_MONTH = createField(DSL.name("term_month"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.loan_application.status</code>.
     */
    public final TableField<LoanApplicationRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.loan_application.created_at</code>.
     */
    public final TableField<LoanApplicationRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.loan_application.updated_at</code>.
     */
    public final TableField<LoanApplicationRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    private LoanApplication(Name alias, Table<LoanApplicationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private LoanApplication(Name alias, Table<LoanApplicationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.loan_application</code> table reference
     */
    public LoanApplication(String alias) {
        this(DSL.name(alias), LOAN_APPLICATION);
    }

    /**
     * Create an aliased <code>public.loan_application</code> table reference
     */
    public LoanApplication(Name alias) {
        this(alias, LOAN_APPLICATION);
    }

    /**
     * Create a <code>public.loan_application</code> table reference
     */
    public LoanApplication() {
        this(DSL.name("loan_application"), null);
    }

    public <O extends Record> LoanApplication(Table<O> path, ForeignKey<O, LoanApplicationRecord> childPath, InverseForeignKey<O, LoanApplicationRecord> parentPath) {
        super(path, childPath, parentPath, LOAN_APPLICATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LoanApplicationPath extends LoanApplication implements Path<LoanApplicationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> LoanApplicationPath(Table<O> path, ForeignKey<O, LoanApplicationRecord> childPath, InverseForeignKey<O, LoanApplicationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LoanApplicationPath(Name alias, Table<LoanApplicationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LoanApplicationPath as(String alias) {
            return new LoanApplicationPath(DSL.name(alias), this);
        }

        @Override
        public LoanApplicationPath as(Name alias) {
            return new LoanApplicationPath(alias, this);
        }

        @Override
        public LoanApplicationPath as(Table<?> alias) {
            return new LoanApplicationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<LoanApplicationRecord, Integer> getIdentity() {
        return (Identity<LoanApplicationRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<LoanApplicationRecord> getPrimaryKey() {
        return Keys.LOAN_APPLICATION_PKEY;
    }

    @Override
    public List<UniqueKey<LoanApplicationRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.LOAN_APPLICATION_CAR_ID_KEY);
    }

    @Override
    public List<ForeignKey<LoanApplicationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.LOAN_APPLICATION__LOAN_APPLICATION_CAR_ID_FKEY, Keys.LOAN_APPLICATION__LOAN_APPLICATION_USER_ID_FKEY);
    }

    private transient CarPath _car;

    /**
     * Get the implicit join path to the <code>public.car</code> table.
     */
    public CarPath car() {
        if (_car == null)
            _car = new CarPath(this, Keys.LOAN_APPLICATION__LOAN_APPLICATION_CAR_ID_FKEY, null);

        return _car;
    }

    private transient UserPath _user;

    /**
     * Get the implicit join path to the <code>public.user</code> table.
     */
    public UserPath user() {
        if (_user == null)
            _user = new UserPath(this, Keys.LOAN_APPLICATION__LOAN_APPLICATION_USER_ID_FKEY, null);

        return _user;
    }

    private transient ApplicationHistoryPath _applicationHistory;

    /**
     * Get the implicit to-many join path to the
     * <code>public.application_history</code> table
     */
    public ApplicationHistoryPath applicationHistory() {
        if (_applicationHistory == null)
            _applicationHistory = new ApplicationHistoryPath(this, null, Keys.APPLICATION_HISTORY__APPLICATION_HISTORY_APPLICATION_ID_FKEY.getInverseKey());

        return _applicationHistory;
    }

    @Override
    public LoanApplication as(String alias) {
        return new LoanApplication(DSL.name(alias), this);
    }

    @Override
    public LoanApplication as(Name alias) {
        return new LoanApplication(alias, this);
    }

    @Override
    public LoanApplication as(Table<?> alias) {
        return new LoanApplication(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public LoanApplication rename(String name) {
        return new LoanApplication(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LoanApplication rename(Name name) {
        return new LoanApplication(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public LoanApplication rename(Table<?> name) {
        return new LoanApplication(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoanApplication where(Condition condition) {
        return new LoanApplication(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoanApplication where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoanApplication where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoanApplication where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LoanApplication where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LoanApplication where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LoanApplication where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LoanApplication where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoanApplication whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoanApplication whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
