/*
 * This file is generated by jOOQ.
 */
package com.financial.loan.persistence.model.tables;


import com.financial.loan.persistence.model.Keys;
import com.financial.loan.persistence.model.Public;
import com.financial.loan.persistence.model.tables.User.UserPath;
import com.financial.loan.persistence.model.tables.records.UserAdditionalDataRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserAdditionalData extends TableImpl<UserAdditionalDataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_additional_data</code>
     */
    public static final UserAdditionalData USER_ADDITIONAL_DATA = new UserAdditionalData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserAdditionalDataRecord> getRecordType() {
        return UserAdditionalDataRecord.class;
    }

    /**
     * The column <code>public.user_additional_data.id</code>.
     */
    public final TableField<UserAdditionalDataRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.user_additional_data.user_id</code>.
     */
    public final TableField<UserAdditionalDataRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.user_additional_data.birthday</code>.
     */
    public final TableField<UserAdditionalDataRecord, LocalDate> BIRTHDAY = createField(DSL.name("birthday"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.user_additional_data.passport_series</code>.
     */
    public final TableField<UserAdditionalDataRecord, String> PASSPORT_SERIES = createField(DSL.name("passport_series"), SQLDataType.VARCHAR(4), this, "");

    /**
     * The column <code>public.user_additional_data.passport_number</code>.
     */
    public final TableField<UserAdditionalDataRecord, String> PASSPORT_NUMBER = createField(DSL.name("passport_number"), SQLDataType.VARCHAR(6), this, "");

    /**
     * The column <code>public.user_additional_data.monthly_income</code>.
     */
    public final TableField<UserAdditionalDataRecord, Double> MONTHLY_INCOME = createField(DSL.name("monthly_income"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.user_additional_data.created_at</code>.
     */
    public final TableField<UserAdditionalDataRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.user_additional_data.updated_at</code>.
     */
    public final TableField<UserAdditionalDataRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    private UserAdditionalData(Name alias, Table<UserAdditionalDataRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserAdditionalData(Name alias, Table<UserAdditionalDataRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.user_additional_data</code> table
     * reference
     */
    public UserAdditionalData(String alias) {
        this(DSL.name(alias), USER_ADDITIONAL_DATA);
    }

    /**
     * Create an aliased <code>public.user_additional_data</code> table
     * reference
     */
    public UserAdditionalData(Name alias) {
        this(alias, USER_ADDITIONAL_DATA);
    }

    /**
     * Create a <code>public.user_additional_data</code> table reference
     */
    public UserAdditionalData() {
        this(DSL.name("user_additional_data"), null);
    }

    public <O extends Record> UserAdditionalData(Table<O> path, ForeignKey<O, UserAdditionalDataRecord> childPath, InverseForeignKey<O, UserAdditionalDataRecord> parentPath) {
        super(path, childPath, parentPath, USER_ADDITIONAL_DATA);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserAdditionalDataPath extends UserAdditionalData implements Path<UserAdditionalDataRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserAdditionalDataPath(Table<O> path, ForeignKey<O, UserAdditionalDataRecord> childPath, InverseForeignKey<O, UserAdditionalDataRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserAdditionalDataPath(Name alias, Table<UserAdditionalDataRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserAdditionalDataPath as(String alias) {
            return new UserAdditionalDataPath(DSL.name(alias), this);
        }

        @Override
        public UserAdditionalDataPath as(Name alias) {
            return new UserAdditionalDataPath(alias, this);
        }

        @Override
        public UserAdditionalDataPath as(Table<?> alias) {
            return new UserAdditionalDataPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<UserAdditionalDataRecord, Integer> getIdentity() {
        return (Identity<UserAdditionalDataRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserAdditionalDataRecord> getPrimaryKey() {
        return Keys.USER_ADDITIONAL_DATA_PKEY;
    }

    @Override
    public List<UniqueKey<UserAdditionalDataRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.USER_ADDITIONAL_DATA_USER_ID_KEY);
    }

    @Override
    public List<ForeignKey<UserAdditionalDataRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USER_ADDITIONAL_DATA__USER_ADDITIONAL_DATA_USER_ID_FKEY);
    }

    private transient UserPath _user;

    /**
     * Get the implicit join path to the <code>public.user</code> table.
     */
    public UserPath user() {
        if (_user == null)
            _user = new UserPath(this, Keys.USER_ADDITIONAL_DATA__USER_ADDITIONAL_DATA_USER_ID_FKEY, null);

        return _user;
    }

    @Override
    public UserAdditionalData as(String alias) {
        return new UserAdditionalData(DSL.name(alias), this);
    }

    @Override
    public UserAdditionalData as(Name alias) {
        return new UserAdditionalData(alias, this);
    }

    @Override
    public UserAdditionalData as(Table<?> alias) {
        return new UserAdditionalData(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAdditionalData rename(String name) {
        return new UserAdditionalData(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAdditionalData rename(Name name) {
        return new UserAdditionalData(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAdditionalData rename(Table<?> name) {
        return new UserAdditionalData(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAdditionalData where(Condition condition) {
        return new UserAdditionalData(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAdditionalData where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAdditionalData where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAdditionalData where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAdditionalData where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAdditionalData where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAdditionalData where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAdditionalData where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAdditionalData whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAdditionalData whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
